
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Updates a specific field in the conversion state.
 * 
 * # Arguments
 * * `input` - Key-value pair specifying which state field to update and its new value
 * * `state` - Application state containing conversion parameters
 * 
 * # Returns
 * * `EResult<BaseResponse>` - Success response with execution duration
 */
async convStateSet(input: ConvStateKey) : Promise<Result<BaseResponse<null>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_state_set", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves the complete current conversion state.
 * 
 * # Arguments
 * * `state` - Application state containing conversion parameters
 * 
 * # Returns
 * * `EResult<BaseResponse<ConvState>>` - Success response containing the current state
 */
async convStateGet() : Promise<Result<BaseResponse<ConvState>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_state_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resets the conversion state to default values.
 * 
 * # Arguments
 * * `state` - Application state containing conversion parameters
 * 
 * # Returns
 * * `EResult<BaseResponse>` - Success response with execution duration
 */
async convStateReset() : Promise<Result<BaseResponse<null>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_state_reset") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyzes the source directory structure for conversion preparation.
 * 
 * Performs comprehensive validation and analysis of the source directory:
 * - Checks for proper directory structure and naming conventions
 * - Validates file formats and permissions
 * - Detects potential issues with file sizes, naming, and special characters
 * - Provides guidance on optimal bundling approaches
 * 
 * # Arguments
 * * `state` - Application state containing conversion parameters
 * 
 * # Returns
 * * `EResult<CommAnalyzeMeta>` - Analysis results with positive findings, warnings, and errors
 */
async convAnalyze() : Promise<Result<BaseResponse<AnalyzeResponse>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_analyze") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bundles chapters into volumes based on directory structure or image analysis.
 * 
 * This function collects all chapters, sorts them according to the bundling strategy,
 * and organizes them into volumes. The strategy depends on the `bundle_flag`:
 * - `Manual`: Basic sorting by numeric values in filenames
 * - `Name`: Intelligent sorting using volume-chapter naming conventions
 * - `Image`: Advanced sorting using grayscale detection to identify volume boundaries
 * 
 * # Arguments
 * * `sensibility` - Optional sensitivity parameter for image analysis (0-100)
 * * `state` - Application state containing conversion parameters
 * 
 * # Returns
 * * `EResult<CommBundle>` - Bundle information including chapter counts and volume distribution
 */
async convBundle(sensibility: number | null) : Promise<Result<BaseResponse<BundleResponse>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_bundle", { sensibility }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Converts bundled volumes into the specified output format.
 * 
 * Processes volumes with concurrency control, generating output files in either
 * CBZ or EPUB format. Emits progress events to the frontend for real-time tracking.
 * 
 * # Arguments
 * * `state` - Application state containing conversion parameters
 * * `app` - Tauri application handle for event emission
 * 
 * # Returns
 * * `EResult<BaseResponse>` - Success response with execution duration
 */
async convConvert() : Promise<Result<BaseResponse<null>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conv_convert") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves the path to the application log files.
 * 
 * # Arguments
 * * `app_handle` - Tauri application handle
 * 
 * # Returns
 * * `EResult<BaseResponse<LogPath>>` - Path information for log files
 */
async mgmtGetLogsPath() : Promise<Result<BaseResponse<LogPath>, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mgmt_get_logs_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
conversionCompleteEvent: ConversionCompleteEvent,
conversionStartEvent: ConversionStartEvent,
imageProgressEvent: ImageProgressEvent,
statusMessageEvent: StatusMessageEvent,
volumeCompleteEvent: VolumeCompleteEvent,
volumeStartEvent: VolumeStartEvent
}>({
conversionCompleteEvent: "conversion-complete-event",
conversionStartEvent: "conversion-start-event",
imageProgressEvent: "image-progress-event",
statusMessageEvent: "status-message-event",
volumeCompleteEvent: "volume-complete-event",
volumeStartEvent: "volume-start-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Analysis operation results.
 */
export type AnalyzeResponse = { negative: string[]; positive: string[]; warning: string[]; flag: BundleFlag }
/**
 * Base response structure with optional payload.
 */
export type BaseResponse<T> = { duration: number; comment: string | null; payload: T | null }
/**
 * File bundling method.
 */
export type BundleFlag = "NAME" | "IMAGE" | "MANUAL"
/**
 * Bundling operation results.
 */
export type BundleResponse = { total_chapters: number; total_volumes: number | null; chapter_sizes: number[] | null }
/**
 * Conversion state for the application.
 */
export type ConvState = { 
/**
 * Name of the conversion task.
 */
name: string; 
/**
 * Source directory or file path.
 */
source: string; 
/**
 * Target directory for output files.
 */
target: string; 
/**
 * Method used for bundling files.
 */
bundle_flag: BundleFlag; 
/**
 * Reading direction (LTR or RTL).
 */
direction: Direction; 
/**
 * Output file format (EPUB or CBZ).
 */
format: FileFormat; 
/**
 * Whether to create a new directory for output.
 */
create_directory: boolean; 
/**
 * Whether to convert images to WebP format (deprecated, use image_format instead).
 */
convert_to_webp: boolean; 
/**
 * Image output format for conversion.
 */
image_format: ImageOutputFormat; 
/**
 * Sizes for volume splitting.
 */
volume_sizes: number[]; 
/**
 * Collection of file paths organized for processing.
 */
data: string[][]; 
/**
 * Optional edited version of the data collection.
 */
edited_data: string[][] | null; 
/**
 * Whether to hide the volume number when there's only one volume.
 */
hide_single_volume_number: boolean; 
/**
 * Custom separator string between project name and volume number.
 */
volume_separator?: string;
/**
 * Whether to flatten all chapters into a single volume.
 */
flatten: boolean }
/**
 * Conversion state property keys.
 */
export type ConvStateKey = { Name: string } | { Source: string } | { Target: string } | { BundleFlag: BundleFlag } | { Direction: Direction } | { Format: FileFormat } | { CreateDirectory: boolean } | { ConvertToWebp: boolean } | { ImageFormat: ImageOutputFormat } | { VolumeSizes: number[] } | { Data: string[][] } | { EditedData: string[][] | null } | { HideSingleVolumeNumber: boolean } | { VolumeSeparator: string } | { Flatten: boolean }
/**
 * Emitted when all conversions complete
 */
export type ConversionCompleteEvent = { total_volumes: number; successful: number; failed: number; duration_seconds: number }
/**
 * Emitted when conversion batch starts
 */
export type ConversionStartEvent = { total_volumes: number }
/**
 * Reading direction for ePub content.
 */
export type Direction = "Left to Right" | "Right to Left"
/**
 * Application error types.
 */
export type Error = 
/**
 * I/O error.
 */
{ type: "Io" } | 
/**
 * Regular expression error.
 */
{ type: "Regex" } | 
/**
 * Tauri framework error.
 */
{ type: "Tauri" } | 
/**
 * Image processing error.
 */
{ type: "Image" } | 
/**
 * EPUB generation error.
 */
{ type: "Epub" } | 
/**
 * ZIP operation error.
 */
{ type: "Zip" } | 
/**
 * Invalid file or directory path.
 */
{ type: "InvalidPath"; data: [string, string] } | 
/**
 * Asynchronous task failure.
 */
{ type: "AsyncTaskError"; data: string } | 
/**
 * Unsupported operation or format.
 */
{ type: "Unsupported"; data: string }
/**
 * Output file format.
 */
export type FileFormat = "EPUB" | "CBZ"
/**
 * Image output format for conversion.
 */
export type ImageOutputFormat = "None" | "WebP" | "AVIF"
/**
 * Emitted periodically to show image processing progress
 */
export type ImageProgressEvent = { volume_index: number; volume_name: string; current_image: number; total_images: number }
/**
 * Path information for application log files.
 */
export type LogPath = { 
/**
 * Directory where log files are stored.
 */
directory: string; 
/**
 * Full path to the main log file.
 */
file: string }
/**
 * Emitted for live status updates during conversion
 */
export type StatusMessageEvent = { message: StatusMessageType; timestamp: number }
/**
 * Status message types for live feedback
 */
export type StatusMessageType = { type: "volume_started"; volume_index: number; volume_name: string } | { type: "page_added"; volume_index: number; volume_name: string; page_number: number; total_pages: number } | { type: "volume_finished"; volume_index: number; volume_name: string; success: boolean }
/**
 * Emitted when a volume conversion completes
 */
export type VolumeCompleteEvent = { volume_index: number; total_volumes: number; volume_name: string; success: boolean; error_message: string | null }
/**
 * Emitted when a volume conversion starts
 */
export type VolumeStartEvent = { volume_index: number; total_volumes: number; volume_name: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
