// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
	async convStateSet(input: ConvStateKey): Promise<Result<BaseResponse<null>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('conv_state_set', { input }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convStateGet(): Promise<Result<BaseResponse<ConvState>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('conv_state_get') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convStateReset(): Promise<Result<BaseResponse<null>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('conv_state_reset') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convAnalyze(): Promise<Result<BaseResponse<AnalyzeResponse>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('conv_analyze') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convBundle(
		sensibility: number | null
	): Promise<Result<BaseResponse<BundleResponse>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('conv_bundle', { sensibility }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convConvert(
		createDirectory: boolean,
		target: string,
		fileFormat: FileFormat,
		direction: Direction
	): Promise<Result<BaseResponse<null>, Error>> {
		try {
			return {
				status: 'ok',
				data: await TAURI_INVOKE('conv_convert', { createDirectory, target, fileFormat, direction })
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async getAgentList(): Promise<Result<BaseResponse<AgentMeta[]>, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('get_agent_list') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	}
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AgentMeta = { name: string; url: string; icon: string | null; tags: TagType[] };
export type AnalyzeResponse = {
	negative: string[];
	positive: string[];
	suggest: string[];
	flag: BundleFlag;
};
export type BaseResponse<T> = { duration: number; comment: string | null; payload: T | null };
export type BundleFlag = 'NAME' | 'IMAGE' | 'MANUAL';
export type BundleResponse = {
	total_chapters: number;
	total_volumes: number | null;
	chapter_sizes: number[] | null;
};
export type ConvState = {
	name: string;
	source: string;
	target: string;
	bundle_flag: BundleFlag;
	direction: Direction;
	format: FileFormat;
	create_directory: boolean;
	volume_sizes: number[];
	data: string[][];
};
export type ConvStateKey =
	| { Name: string }
	| { Source: string }
	| { BundleFlag: BundleFlag }
	| { Direction: Direction }
	| { Format: FileFormat }
	| { CreateDirectory: boolean }
	| { VolumeSizes: number[] }
	| { Data: string[][] };
export type Direction = 'Left to Right' | 'Right to Left';
export type Error =
	| { type: 'Io' }
	| { type: 'Regex' }
	| { type: 'Tauri' }
	| { type: 'Image' }
	| { type: 'Epub' }
	| { type: 'Zip' }
	| { type: 'PrintPdf' }
	| { type: 'PrintPdfImage' }
	| { type: 'Reqwest' }
	| { type: 'InvalidPath'; data: [string, string] }
	| { type: 'AsyncTaskError'; data: string }
	| { type: 'Unsupported'; data: string }
	| { type: 'NotFound'; data: string };
export type FileFormat = 'PDF' | 'EPUB' | 'CBZ';
export type StatusFlag = 'Experimental' | 'Deprecated' | 'Stable';
export type TagType = { Language: string } | { Status: StatusFlag } | { Other: string };

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
	listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg)
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case 'listen':
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case 'once':
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case 'emit':
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					}
				});
			}
		}
	);
}
