[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
specta.workspace = true
tauri-specta.workspace = true
log.workspace = true
sysinfo.workspace = true
num_cpus.workspace = true
regex.workspace = true
lazy_static.workspace = true
image.workspace = true
tauri.workspace = true
zip.workspace = true
epub-builder.workspace = true
