// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
	async setSource(source: string): Promise<Result<CommandDefault, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('set_source', { source }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async setBundleFlag(flag: BundleFlag): Promise<Result<CommandDefault, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('set_bundle_flag', { flag }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async setData(data: string[][]): Promise<Result<CommandDefault, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('set_data', { data }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async setVolumeSizes(sizes: number[]): Promise<Result<CommandDefault, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('set_volume_sizes', { sizes }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async getData(): Promise<Result<CommandGetData, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('get_data') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async reset(): Promise<Result<CommandDefault, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('reset') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async analyze(): Promise<Result<CommandAnalyze, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('analyze') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async bundle(sensibility: number | null): Promise<Result<CommandBundle, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('bundle', { sensibility }) };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async convert(
		createDirectory: boolean,
		target: string,
		fileFormat: FileFormat,
		direction: Direction
	): Promise<Result<CommandDefault, Error>> {
		try {
			return {
				status: 'ok',
				data: await TAURI_INVOKE('convert', { createDirectory, target, fileFormat, direction })
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	},
	async getAgentList(): Promise<Result<CommandListAgents, Error>> {
		try {
			return { status: 'ok', data: await TAURI_INVOKE('get_agent_list') };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: 'error', error: e as any };
		}
	}
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AgentMeta = { name: string; url: string; icon: string | null; tags: string[] };
export type BundleFlag = 'NAME' | 'IMAGE' | 'MANUAL';
export type CommandAnalyze = {
	message: string | null;
	negative: string[];
	positive: string[];
	suggest: string[];
	flag: BundleFlag;
};
export type CommandBundle = {
	message: string | null;
	total_chapters: number;
	total_volumes: number | null;
	chapter_sizes: number[] | null;
};
export type CommandDefault = { message: string | null };
export type CommandGetData = { message: string | null; data: string[][] };
export type CommandListAgents = { message: string | null; agents: AgentMeta[] };
export type Direction = 'Left to Right' | 'Right to Left';
export type Error =
	| { type: 'Io' }
	| { type: 'Regex' }
	| { type: 'Tauri' }
	| { type: 'Image' }
	| { type: 'Epub' }
	| { type: 'Zip' }
	| { type: 'PrintPdf' }
	| { type: 'PrintPdfImage' }
	| { type: 'Reqwest' }
	| { type: 'InvalidPath'; data: [string, string] }
	| { type: 'AsyncTaskError'; data: string }
	| { type: 'Unsupported'; data: string }
	| { type: 'NotFound'; data: string };
export type FileFormat = 'PDF' | 'EPUB' | 'CBZ';

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
	listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg)
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case 'listen':
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case 'once':
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case 'emit':
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					}
				});
			}
		}
	);
}
